SportsStore/Models/Cart.cs
using Microsoft.AspNetCore.Http;
using SportsStore.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportsStore.Models
{
    public class Cart
    {
        private ISession storage;

        private Dictionary<Guid, CartItem> cart;

        public virtual IEnumerable<CartItem> Items { get => cart.Values; }

        public virtual decimal Total { get => Items.Sum(ci => ci.Product.Price * ci.Quantity); }

        public Cart(ISession storage) : this(storage, new CartItem[0])
        {
        }

        public Cart(ISession storage, CartItem[] items)
        {
            this.storage = storage;
            cart = items.ToDictionary(ci => ci.Product.Id);
            Save();
        }

        public virtual void Add(Product product)
        {
            if (cart.ContainsKey(product.Id))
            {
                cart[product.Id].Quantity++;
            }
            else
            {
                cart[product.Id] = new CartItem(product);
            }

            Save();
        }

        public virtual void Clear()
        {
            cart.Clear();

            storage.Remove(nameof(Cart));
        }

        public virtual void Remove(Guid id)
        {
            cart.Remove(id);

            Save();
        }

        public void ModifyQuantity(Guid id, int qty)
        {
            if (qty <= 0)
            {
                cart.Remove(id);
            }
            else if(cart.ContainsKey(id))
            {
                cart[id].Quantity = qty;
            }

            Save();
        }

        private void Save()
        {
            storage.SaveCart(this);
        }
    }
}

SportsStore/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using SportsStore.Models;
using SportsStore.Services;

namespace SportsStore.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;

        private Cart cart;

        public CartController(IProductRepository repository, Cart cart)
        {
            this.repository = repository;
            this.cart = cart;
        }

        public IActionResult Index()
        {
            return View(cart);
        }

        public IActionResult AddToCart(Guid id)
        {
            var product = repository.Products.Single(p => p.Id == id);

            cart.Add(product);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult RemoveFromCart(Guid id)
        {
            cart.Remove(id);;

            return RedirectToAction(nameof(Index));
        }
    }
}

SportsStore/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Controllers
{
    public class OrderController : Controller
    {
        private Cart cart;

        private IOrderRepository repository;

        public OrderController(IOrderRepository repository, Cart cart)
        {
            this.cart = cart;
            this.repository = repository;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public IActionResult Checkout(ShippingDetails details)
        {
            if (cart.Items.Count() == 0)
            {
                ModelState.AddModelError("CartEmpty", "Sorry, your cart is empty");
            }

            if (ModelState.IsValid)
            {
                var order = new Order(details, cart);

                repository.SaveOrder(order);

                return RedirectToAction(nameof(Completed));
            }
            else
            {
                return View(details);
            }
        }

        public IActionResult Completed()
        {
            cart.Clear();

            return View();
        }
    }
}

SportsStore/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using SportsStore.Models.ViewModel;

namespace SportsStore.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;
        public int PageSize { get; set; } = 3;

        public ProductController(IProductRepository repository)
        {
            this.repository = repository;
        }

        public IActionResult List(string category = null, int page = 1)
        {
            var result = repository.Products
                                    .Where(p => string.IsNullOrWhiteSpace(category) || 
                                                p.Category.ToLower() == category.ToLower())
                                    .OrderBy(p => p.Id);

            ViewBag.PagingInfo = new PagingInfo { Current = page, PerPage = PageSize, Total = result.Count() };
            ViewBag.Category = category;

            return View(
                result.Skip((page - 1) * PageSize)
                        .Take(PageSize)
            );
        }
    }
}

SportsStore/Views/Cart/Index.cshtml
@model Cart

@{
    Layout = "_Layout";
}

<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Your Cart</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <td>Quantity</td>
                <td>Item</td>
                <td>Price</td>
                <td>Subtotal</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Items)
            {
            <tr>
                <td>@item.Quantity</td>
                <td>@item.Product.Name</td>
                <td>@item.Product.Price.ToString("c")</td>
                <td>@((item.Product.Price * item.Quantity).ToString("c"))</td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart", new { Id = item.Product.Id }, FormMethod.Post))
                    {
                        <button type="submit" class="btn btn-danger">Remove</button>
                    }
                </td>
            </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3">Total:</td>
                <td>@Model.Total.ToString("c")</td>
                <td></td>
            </tr>
        </tfoot>
    </table>
</div>

<div class="center-block">
    @Html.ActionLink("Continue Shopping", "List", "Product", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Checkout", "Checkout", "Order", null, new { @class = "btn btn-success" })
</div>