SportsStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Services;
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportsStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;

        public CartSummaryViewComponent(Cart cart)
        {
            this.cart = cart;
        }

        public IViewComponentResult Invoke()
        {
            return View(new CartSummary { Show = cart.Total > 0, Items = cart.Items.Sum(p => p.Quantity), Total = cart.Total });
        }
    }

    public class CartSummary
    {
        public bool Show { get; set; }
        public int Items { get; set; }
        public decimal Total { get; set; }
    }
}

SportsStore/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportsStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IProductRepository repository;

        public NavigationMenuViewComponent(IProductRepository repository)
        {
            this.repository = repository;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.Selected = RouteData.Values["category"];

            var result = repository.Products.Select(p => p.Category).Distinct().OrderBy(p => p);

            return View(result);
        }
    }
}

SportsStore/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using SportsStore.Models;
using SportsStore.Services;

namespace SportsStore.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;

        private Cart cart;

        public CartController(IProductRepository repository, Cart cart)
        {
            this.repository = repository;
            this.cart = cart;
        }

        public IActionResult Index()
        {
            return View(cart);
        }

        public IActionResult AddToCart(Guid id)
        {
            var product = repository.Products.Single(p => p.Id == id);

            cart.Add(product);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult RemoveFromCart(Guid id)
        {
            cart.Remove(id);;

            return RedirectToAction(nameof(Index));
        }
    }
}

SportsStore/Views/Shared/ProductSummary.cshtml
@model Product

<div class="bg-faded">
    <h4>
        @Model.Name
        <span class="badge">
            @Model.Price.ToString("c")
        </span>
    </h4>
</div>
<div> @Model.Description</div>

@using(Html.BeginForm("AddToCart", "Cart", new { Id = Model.Id }, FormMethod.Post))
{
    <button type="submit" class="btn btn-success">Add To Cart</button>
}

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <title>SportsStore</title>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid navbar-inverse bg-inverse" role="navigation">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">SPORTS STORE</a>
            </div>
            <div>
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
    {
                <li><a class="btn" href="@Url.Action("Logout", "Account", new { area = "" })"><i class="fa fa-user-times" aria-hidden="true"></i></a></li>
}
else
{
                <li><a class="btn" href="@Url.Action("Login", "Account", new { area = "" })"><i class="fa fa-user-o" aria-hidden="true"></i></a></li>
}

                    <li><a class="btn" href="@Url.Action("List", "Shipping", new { area = "admin" })"><i class="fa fa-truck" aria-hidden="true"></i></a></li>
                    <li><a class="btn" href="@Url.Action("Index", "Stock", new { area = "admin" })"><i class="fa fa-wrench" aria-hidden="true"></i></a></li>
                    @await Component.InvokeAsync("CartSummary")
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div id="categories" class="col-sm-2">
                @await Component.InvokeAsync("NavigationMenu")
            </div>
            <div class="col-sm-10">
                @RenderBody()
            </div>

        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>