SportsStore/Areas/Admin/Controllers/ShippingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class ShippingController : Controller
    {
        private IOrderRepository repository;

        public ShippingController(IOrderRepository repoService)
        {
            repository = repoService;
        }

        public ViewResult List() =>
            View(repository.Orders.Where(o => !o.Shipped));

        [HttpPost]
        public IActionResult MarkShipped(Guid id)
        {
            var order = repository.Orders.Single(o => o.Id == id);

            order.Shipped = true;
            repository.SaveOrder(order);

            return RedirectToAction(nameof(List));
        }
    }
}

SportsStore/Areas/Admin/Views/Shipping/List.cshtml
@model IEnumerable<Order>

@{
    ViewData["Title"] = "List";
    Layout = "_Layout";
}

@if (Model.Count() > 0)
{
    <table class="table table-bordered table-striped">
        <tr><th>Name</th><th>Zip</th><th colspan="2">Details</th><th></th></tr>
        @foreach (var o in Model)
        {
            <tr>
                <td>@o.Details.Name</td>
                <td>@o.Details.Zip</td>
                <th>Product</th>
                <th>Quantity</th>
                <td>
                    @using (Html.BeginForm("MarkShipped", "Shipping", new { area = "Admin", id = @o.Id }, FormMethod.Post))
                    {
                        <button type="submit" class="btn btn-sm btn-danger">
                            Ship
                        </button>
                    }
                </td>
            </tr>
            @foreach (var line in o.Items)
            {
                <tr>
                    <td colspan="2"></td>
                    <td>@line.Product.Name</td>
                    <td>@line.Quantity</td>
                    <td></td>
                </tr>
            }
        }
    </table>
}
else
{
    <div class="text-center">No Unshipped Orders</div>
}